# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'homework-7' do
  pod 'SnapKit'
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for homework-7

end
